import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Legends Race Engine | Do GPS ao resultado",
  description: "Conheça a tecnologia própria da Legends para validar percursos, checkpoints, tempos e resultados da Gravel Race e a jornada do modo Experience.",
};

const steps = [
  ["01", "Pedale", "Registre a etapa normalmente no seu dispositivo GPS."],
  ["02", "Sincronize", "Conecte sua atividade ao Legends Passport."],
  ["03", "Valide", "O sistema compara percurso, checkpoints e regras da etapa."],
  ["04", "Acompanhe", "Veja passagens, situação da análise e evolução na prova."],
  ["05", "Comprove", "O resultado aprovado integra a classificação ou o histórico da jornada."],
];

const capabilities = [
  ["⌁", "Percurso oficial", "Compara a linha registrada pelo GPS com a rota homologada pela organização."],
  ["◎", "Checkpoints digitais", "Identifica passagens em pontos estratégicos e apresenta a progressão na etapa."],
  ["◷", "Tempos intermediários", "Registra os tempos de passagem e calcula o tempo oficial entre largada e chegada."],
  ["✓", "Apuração esportiva", "Centraliza revisão, aprovação, penalidade, justificativa e bloqueio do resultado."],
  ["≡", "Classificação", "Organiza resultados por etapa, categoria e classificação geral ponderada por pontos."],
  ["↗", "Publicação", "Entrega uma página pública para acompanhar resultados provisórios e oficiais."],
];

export default function RaceEnginePage() {
  return (
    <main className="enginePage">
      <style>{`
        .enginePage{--ink:#090b0a;--panel:#111411;--paper:#f2ecdf;--orange:#cf6815;--line:rgba(207,104,21,.34);background:var(--ink);color:#f2ede5;min-height:100vh}
        .engineShell{width:min(1420px,calc(100% - 96px));margin:auto}.engineNav{height:92px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid rgba(242,237,229,.13)}.engineNav img{width:72px;height:64px;object-fit:contain}.engineNav a{color:#f2ede5;text-transform:uppercase;letter-spacing:.12em;font:700 14px 'Barlow Condensed'}.engineNav a:first-child{color:var(--orange)}
        .engineHero{padding:105px 0 84px;background:radial-gradient(circle at 78% 28%,rgba(207,104,21,.17),transparent 31%)}.eyebrow{margin:0 0 20px;color:var(--orange);font:700 14px 'Barlow Condensed';letter-spacing:.22em;text-transform:uppercase}.engineHeroGrid{display:grid;grid-template-columns:1.25fr .75fr;gap:80px;align-items:end}.engineHero h1{margin:0;font:700 clamp(66px,7vw,112px)/.86 'Barlow Condensed';letter-spacing:-.025em;text-transform:uppercase}.engineHero h1 em{display:block;color:var(--orange);font-style:normal}.engineLead{margin:0;color:#acb1a9;font-size:18px;line-height:1.75}.enginePromise{margin-top:70px;padding:27px 30px;border:1px solid var(--line);display:grid;grid-template-columns:1fr auto;gap:30px;align-items:center;background:rgba(17,20,17,.72)}.enginePromise strong{font:700 26px 'Barlow Condensed';text-transform:uppercase}.enginePromise span{color:#adb2aa}.enginePromise b{color:var(--orange);font:700 15px 'Barlow Condensed';letter-spacing:.11em;text-transform:uppercase}
        .journey{padding:100px 0;background:#111411}.sectionHead{display:grid;grid-template-columns:1.15fr .85fr;gap:70px;align-items:end;margin-bottom:45px}.sectionHead h2{font:700 clamp(48px,5vw,76px)/.92 'Barlow Condensed';text-transform:uppercase;margin:0}.sectionHead h2 em{color:var(--orange);font-style:normal}.sectionHead>p{color:#9da29a;line-height:1.7;margin:0}.stepGrid{display:grid;grid-template-columns:repeat(5,1fr);border:1px solid var(--line)}.step{min-height:245px;padding:27px 23px;border-right:1px solid var(--line)}.step:last-child{border:0}.step>span{color:var(--orange);font:700 13px 'Barlow Condensed';letter-spacing:.16em}.step h3{font:700 31px 'Barlow Condensed';text-transform:uppercase;margin:55px 0 13px}.step p{font-size:14px;line-height:1.6;color:#989e95;margin:0}
        .capabilities{padding:110px 0;background:var(--paper);color:#101210}.capabilities .sectionHead>p{color:#666b64}.capGrid{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid #bdb3a5;border-left:1px solid #bdb3a5}.cap{padding:31px;min-height:220px;border-right:1px solid #bdb3a5;border-bottom:1px solid #bdb3a5}.capIcon{display:grid;place-items:center;width:38px;height:38px;color:var(--orange);border:1px solid var(--orange);font-size:19px}.cap h3{font:700 27px 'Barlow Condensed';text-transform:uppercase;margin:26px 0 10px}.cap p{color:#5b6059;line-height:1.65;margin:0;font-size:14px}
        .modesCompare{padding:110px 0;background:#090b0a}.modeIntro{text-align:center;max-width:860px;margin:0 auto 48px}.modeIntro h2{font:700 clamp(48px,5vw,76px)/.92 'Barlow Condensed';text-transform:uppercase;margin:0}.modeIntro h2 em{font-style:normal;color:var(--orange)}.modeIntro p:last-child{color:#9da29a;line-height:1.7}.modeGrid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.mode{padding:43px;border:1px solid var(--line);background:#111411}.mode.experience{background:var(--paper);color:#111411;border-color:var(--paper)}.tag{color:var(--orange);font:700 13px 'Barlow Condensed';letter-spacing:.16em;text-transform:uppercase}.mode h3{font:700 43px 'Barlow Condensed';text-transform:uppercase;margin:18px 0 14px}.mode p{color:#9ca198;line-height:1.68}.mode.experience p{color:#5c605a}.mode ul{list-style:none;padding:0;margin:28px 0 0;display:grid;gap:12px}.mode li{padding-top:12px;border-top:1px solid var(--line)}.mode li:before{content:'✓';color:var(--orange);margin-right:12px}.modeNote{margin-top:25px;padding:18px 20px;background:rgba(207,104,21,.1);font-size:14px;line-height:1.6}
        .integrity{padding:105px 0;background:#111411}.integrityGrid{display:grid;grid-template-columns:.85fr 1.15fr;gap:90px;align-items:start}.integrity h2{font:700 clamp(48px,5vw,76px)/.92 'Barlow Condensed';text-transform:uppercase;margin:0}.integrity h2 em{font-style:normal;color:var(--orange)}.integrityList{border-top:1px solid var(--line)}.integrityList article{display:grid;grid-template-columns:50px 1fr;gap:20px;padding:22px 0;border-bottom:1px solid var(--line)}.integrityList span{color:var(--orange);font-size:23px}.integrityList h3{margin:0 0 7px;font:700 23px 'Barlow Condensed';text-transform:uppercase}.integrityList p{margin:0;color:#999f96;line-height:1.6;font-size:14px}
        .engineCta{padding:130px 0;text-align:center;background:linear-gradient(rgba(8,10,9,.8),rgba(8,10,9,.96)),url('/hero-production.jpg') center/cover}.engineCta h2{font:700 clamp(55px,6vw,90px)/.88 'Barlow Condensed';text-transform:uppercase;margin:0}.engineCta h2 em{font-style:normal;color:var(--orange)}.engineCta p{max-width:680px;margin:25px auto 34px;color:#aeb3ab;line-height:1.7}.engineButton{display:inline-flex;justify-content:space-between;gap:45px;min-width:285px;padding:19px 24px;background:var(--orange);color:#fff;font:700 15px 'Barlow Condensed';text-transform:uppercase;letter-spacing:.08em}
        .engineFooter{height:90px;display:flex;align-items:center;justify-content:space-between;color:#777d74;font-size:12px;text-transform:uppercase;letter-spacing:.11em}
        @media(max-width:980px){.engineShell{width:min(100% - 48px,900px)}.engineHeroGrid,.sectionHead,.integrityGrid{grid-template-columns:1fr}.stepGrid{grid-template-columns:1fr 1fr}.step:nth-child(2n){border-right:0}.capGrid{grid-template-columns:1fr 1fr}.engineHeroGrid,.sectionHead,.integrityGrid{gap:30px}}
        @media(max-width:640px){.engineShell{width:calc(100% - 32px)}.engineNav{height:76px}.engineNav img{width:56px}.engineHero{padding:70px 0 58px}.engineHero h1{font-size:58px}.engineLead{font-size:16px}.enginePromise{grid-template-columns:1fr;padding:21px}.journey,.capabilities,.modesCompare,.integrity{padding:70px 0}.stepGrid,.capGrid,.modeGrid{grid-template-columns:1fr}.step{min-height:0;border-right:0;border-bottom:1px solid var(--line)}.step h3{margin-top:25px}.cap{min-height:0}.mode{padding:30px 25px}.mode h3{font-size:36px}.integrityGrid{gap:36px}.engineCta{padding:90px 0}.engineFooter{height:auto;padding:25px 0;gap:20px;flex-direction:column;align-items:flex-start}}
      `}</style>

      <header className="engineNav engineShell"><a href="/">← Voltar ao site</a><img src="/legends-logo-official.png" alt="Legends Bike Race" /><a href="/acesso">Atleta / Organizador</a></header>

      <section className="engineHero"><div className="engineShell"><p className="eyebrow">Tecnologia própria · Legends Core</p><div className="engineHeroGrid"><h1>Do GPS ao<em>resultado.</em></h1><p className="engineLead">O Legends Race Engine conecta atividades, percurso oficial, checkpoints digitais, apuração esportiva e publicação. A aventura continua livre; o resultado ganha precisão e transparência.</p></div><div className="enginePromise"><div><strong>Você pedala. O Race Engine transforma sua atividade em resultado.</strong><br/><span>Na Gravel Race, ele sustenta a competição. No Experience, registra e valida a jornada.</span></div><b>Cada passagem conta</b></div></div></section>

      <section className="journey"><div className="engineShell"><div className="sectionHead"><div><p className="eyebrow">Como funciona</p><h2>Uma experiência contínua.<br/><em>Cinco passos.</em></h2></div><p>O processo começa no dispositivo do participante e termina em uma informação clara para atleta, organização e público.</p></div><div className="stepGrid">{steps.map(([n,title,text])=><article className="step" key={n}><span>{n}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

      <section className="capabilities"><div className="engineShell"><div className="sectionHead"><div><p className="eyebrow">O que o sistema entrega</p><h2>Controle para a organização.<br/><em>Clareza para o atleta.</em></h2></div><p>Todos os elementos importantes da prova ficam conectados, da inscrição à classificação oficial.</p></div><div className="capGrid">{capabilities.map(([icon,title,text])=><article className="cap" key={title}><span className="capIcon" aria-hidden="true">{icon}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

      <section className="modesCompare"><div className="engineShell"><div className="modeIntro"><p className="eyebrow">Uma tecnologia · duas experiências</p><h2>Competir ou experimentar.<br/><em>O propósito é respeitado.</em></h2><p>O Race Engine adapta a entrega à modalidade escolhida pelo participante.</p></div><div className="modeGrid"><article className="mode"><span className="tag">Modalidade competitiva</span><h3>Legends Gravel Race</h3><p>Para gravel e cyclocross. A atividade homologada gera tempo oficial, pontos, posição na categoria e classificação acumulada.</p><ul><li>Validação do percurso</li><li>Tempos em checkpoints</li><li>Pontuação por etapa</li><li>Ranking por categoria e geral</li><li>Revisão e penalidades justificadas</li></ul></article><article className="mode experience"><span className="tag">Modalidade experiência</span><h3>Legends Experience</h3><p>Para MTB e E-bike. O participante vive os mesmos percursos, cidades e estrutura, sem pressão por colocação.</p><ul><li>MTB e E-bike permitidas</li><li>Jornada vinculada ao Passport</li><li>Registro das etapas concluídas</li><li>Sem ranking ou premiação competitiva</li><li>Certificado pessoal de conclusão</li></ul><div className="modeNote"><strong>Importante:</strong> o Experience pode ter a jornada validada pelo sistema, mas não disputa a classificação da Gravel Race.</div></article></div></div></section>

      <section className="integrity"><div className="engineShell integrityGrid"><div><p className="eyebrow">Transparência esportiva</p><h2>Tecnologia para competir<br/><em>com liberdade.</em></h2></div><div className="integrityList"><article><span>01</span><div><h3>Decisão humana preservada</h3><p>O sistema organiza evidências, mas situações excepcionais continuam sob responsabilidade da direção esportiva.</p></div></article><article><span>02</span><div><h3>Motivos registrados</h3><p>Quando houver penalidade, revisão ou rejeição, a decisão fica acompanhada de seu fundamento.</p></div></article><article><span>03</span><div><h3>Resultado protegido</h3><p>Após a apuração, a etapa pode ser publicada e bloqueada para preservar a versão oficial.</p></div></article><article><span>04</span><div><h3>Segurança sem expor o método</h3><p>O público conhece o processo e os resultados, enquanto critérios antifraude permanecem protegidos.</p></div></article></div></div></section>

      <section className="engineCta"><div className="engineShell"><p className="eyebrow">Legends Race Engine</p><h2>Sua aventura registrada.<br/><em>Seu resultado comprovado.</em></h2><p>Escolha a modalidade que representa seu objetivo e viva a mesma travessia pelas estradas da Serra Gaúcha.</p><a className="engineButton" href="/#modalidades">Conheça as modalidades <span>→</span></a></div></section>
      <footer className="engineFooter engineShell"><span>Legends Bike Race · Serra Gaúcha</span><span>Uma experiência Threerace Sports</span></footer>
    </main>
  );
}
