export default function ListaPrioritaria() {
  return <main className="priorityPage"><style>{`
    .priorityPage{--paper:#f4f0db;--ink:#0b0d0c;--copper:#c67a3b;--line:rgba(198,122,59,.34);min-height:100vh;background:linear-gradient(90deg,rgba(6,8,7,.98),rgba(6,8,7,.78) 45%,rgba(6,8,7,.22)),url('/hero-production.jpg') center/cover;color:#f1ece3}.wrap{width:min(1180px,calc(100% - 80px));margin:auto}
    .top{height:100px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid rgba(241,236,227,.14)}.logo{height:72px}.back{color:var(--copper);font:600 13px 'Barlow Condensed';text-transform:uppercase;letter-spacing:.15em}
    .content{min-height:calc(100vh - 100px);display:grid;grid-template-columns:1.15fr .85fr;gap:80px;align-items:center;padding:70px 0}.kicker{color:var(--copper);font:600 14px 'Barlow Condensed';text-transform:uppercase;letter-spacing:.22em}h1{font:700 clamp(68px,8.5vw,126px) 'Barlow Condensed';text-transform:uppercase;line-height:.84;margin:20px 0 28px}.lead{font-size:19px;line-height:1.75;color:#d5d9d2;max-width:680px}
    .facts{display:grid;grid-template-columns:repeat(2,1fr);gap:1px;background:var(--line);border:1px solid var(--line);margin-top:35px}.fact{background:rgba(11,13,12,.9);padding:20px}.fact strong{display:block;font:700 34px 'Barlow Condensed'}.fact span{font:500 11px 'Barlow Condensed';text-transform:uppercase;letter-spacing:.13em;color:#aaaFA7}
    .panel{background:var(--paper);color:var(--ink);padding:42px}.panel h2{font:700 48px 'Barlow Condensed';text-transform:uppercase;line-height:.92;margin:0 0 16px}.panel p{color:#565a54;line-height:1.7}.panel ul{list-style:none;padding:0;margin:26px 0;display:grid;gap:12px}.panel li:before{content:'✓';color:var(--copper);margin-right:10px}.button{display:block;text-align:center;background:var(--copper);padding:18px 22px;font:700 14px 'Barlow Condensed';text-transform:uppercase;letter-spacing:.12em;margin-top:25px}.note{font-size:12px;color:#777b75!important;text-align:center}
    @media(max-width:850px){.wrap{width:calc(100% - 32px)}.top{height:82px}.logo{height:58px}.content{min-height:auto;grid-template-columns:1fr;gap:45px;padding:70px 0}.panel{padding:32px 24px}}
  `}</style>
  <nav className="top wrap"><a href="/"><img className="logo" src="/legends-logo-official.png" alt="Legends" /></a><a className="back" href="/">← Voltar à Home</a></nav>
  <section className="content wrap"><div><p className="kicker">A primeira edição está sendo construída</p><h1>Seja um dos 100 Legends.</h1><p className="lead">Entre para a lista prioritária e receba antes do público a data oficial, os valores, a abertura das inscrições, os hotéis parceiros e as novidades da primeira edição.</p><div className="facts"><div className="fact"><strong>100</strong><span>vagas previstas</span></div><div className="fact"><strong>04</strong><span>dias de travessia</span></div><div className="fact"><strong>360</strong><span>quilômetros</span></div><div className="fact"><strong>6.000</strong><span>metros de ascensão</span></div></div></div>
  <aside className="panel"><p className="kicker">Lista prioritária</p><h2>Receba as informações primeiro.</h2><p>Enquanto o formulário definitivo não é integrado, o cadastro será realizado diretamente por e-mail com a organização.</p><ul><li>Data oficial</li><li>Abertura das inscrições</li><li>Valores e parcelamento</li><li>Hotéis parceiros</li><li>Informações para atletas estrangeiros</li></ul><a className="button" href="mailto:contato@threerace.com.br?subject=Quero entrar na lista prioritária da Legends&body=Nome:%0D%0ACidade/País:%0D%0ATelefone:%0D%0AModalidade de interesse: Gravel Race ou Legends Experience">Entrar para a lista prioritária →</a><p className="note">O envio do e-mail não representa inscrição confirmada.</p></aside></section>
  </main>;
}