"use client";

import dynamic from "next/dynamic";
import { useEffect, useMemo, useState } from "react";

const ValidationMap=dynamic(()=>import("../validacao/ValidationMap"),{ssr:false});
type Item={id:string;status:string;coverage_percent:number|null;start_ok:boolean|null;finish_ok:boolean|null;direction_ok:boolean|null;checkpoints_passed:number|null;checkpoints_total:number|null;max_deviation_m:number|null;notes:string|null;updated_at:string;athlete?:{full_name?:string;category?:string};stage?:{name?:string;route_label?:string;stage_date?:string};activity?:{id:string;name:string;distance_km:number;elevation_m:number;moving_time_s:number;gps_points:[number,number][]};route?:{version:number;file_name:string;route_points:[number,number][]};checkpoints:any[];passages?:Array<{id:string;checkpoint_id:string;elapsed_s:number;passed_at:string}>;segment_results?:Array<{id:string;elapsed_s:number;status:string;segment?:{name:string;segment_type:string}}>};
const labels:Record<string,string>={validated:"Homologada",review:"Em revisão",rejected:"Não homologada",pending:"Pendente"};
function formatDuration(seconds?:number|null){if(seconds===null||seconds===undefined)return"—";const total=Math.max(0,Math.round(Number(seconds)));const h=Math.floor(total/3600),m=Math.floor((total%3600)/60),s=total%60;return`${h?`${String(h).padStart(2,"0")}:`:""}${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`;}
function formatPassage(value?:string|null){return value?new Date(value).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit",second:"2-digit"}):"—";}

export default function ReviewsPage(){
  const [items,setItems]=useState<Item[]>([]);const [selectedId,setSelectedId]=useState("");const [filter,setFilter]=useState("review");const [note,setNote]=useState("");const [message,setMessage]=useState("");const [saving,setSaving]=useState(false);
  async function load(){const response=await fetch("/api/admin/reviews",{cache:"no-store"});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Falha ao carregar revisões.");setItems(payload.items??[]);const query=new URLSearchParams(window.location.search).get("validation");setSelectedId(current=>current||query||payload.items?.find((item:Item)=>item.status==="review")?.id||payload.items?.[0]?.id||"");}
  useEffect(()=>{load().catch(error=>setMessage(error.message));},[]);
  const filtered=useMemo(()=>filter==="all"?items:items.filter(item=>item.status===filter),[items,filter]);
  const selected=items.find(item=>item.id===selectedId)??null;
  const checkpointById=new Map((selected?.checkpoints??[]).map((checkpoint:any)=>[checkpoint.id,checkpoint]));
  async function decide(decision:"validated"|"rejected"|"review") {if(!selected)return;setSaving(true);setMessage("Registrando decisão...");try{const response=await fetch("/api/admin/reviews",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({validationId:selected.id,decision,note})});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Falha ao registrar decisão.");setNote("");setMessage(decision==="validated"?"Atividade homologada pela organização.":decision==="rejected"?"Atividade rejeitada pela organização.":"Atividade mantida em revisão.");await load();}catch(error){setMessage(error instanceof Error?error.message:"Falha ao registrar decisão.");}finally{setSaving(false);}}
  return <main className="reviews-page"><style>{`
    .reviews-page{min-height:calc(100vh - 72px);background:#0d100d;color:#f2eee5;padding:42px 3vw 80px;font-family:Arial,sans-serif}.reviews-shell{max-width:1440px;margin:auto}.kicker{color:#d47b2d;letter-spacing:.2em;text-transform:uppercase;font-size:12px;font-weight:900}.reviews-head{display:flex;align-items:end;justify-content:space-between;gap:25px}.reviews-head h1{font-size:clamp(42px,5vw,70px);line-height:.9;text-transform:uppercase;margin:13px 0}.reviews-head p{color:#aeb3ab;max-width:580px;line-height:1.7}.filters{display:flex;gap:8px;flex-wrap:wrap;margin:30px 0 18px}.filters button{border:1px solid #474c43;background:#171a16;color:#d8d4cc;padding:10px 14px;cursor:pointer;font-weight:800}.filters button.active{background:#e86619;border-color:#e86619;color:white}.reviews-grid{display:grid;grid-template-columns:360px 1fr;gap:20px}.review-list{display:grid;gap:9px;align-content:start;max-height:900px;overflow:auto}.review-item{border:1px solid #363b34;background:#161916;color:#eee9e1;padding:16px;text-align:left;cursor:pointer}.review-item.active{border-color:#d47b2d;background:#24190f}.review-item strong,.review-item span{display:block}.review-item span{color:#9fa49c;font-size:12px;margin-top:5px}.status-pill{display:inline-block!important;width:max-content;margin-top:10px!important;padding:5px 8px;background:#30362f;color:#efb078!important;font-weight:900;text-transform:uppercase}.detail{background:#eee5d8;color:#171917;padding:28px;min-height:640px}.detail h2{font-size:36px;text-transform:uppercase;margin:8px 0}.detail-sub{color:#656a63}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:20px 0}.metrics div{border:1px solid #c7baaa;padding:14px}.metrics strong{display:block;font-size:24px}.checks{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:16px 0}.check{padding:12px;border:1px solid #c7baaa}.timing-review{margin-top:18px;border:1px solid #c7baaa;background:#fff8ee;padding:17px}.timing-review h3{margin:0 0 12px}.passage-review{display:grid;grid-template-columns:1fr auto auto;gap:14px;padding:9px 0;border-top:1px solid #d8cebf;align-items:center}.passage-review span{font-size:13px;color:#6e6961}.segment-review{display:grid;grid-template-columns:1fr auto;gap:12px;padding:11px 0;border-top:1px solid #d8cebf}.segment-review b{color:#c05d17}.notes{white-space:pre-wrap;background:#f8f1e7;border:1px solid #c7baaa;padding:16px;line-height:1.6;max-height:220px;overflow:auto}.decision{margin-top:22px;border-top:1px solid #c7baaa;padding-top:20px}.decision textarea{width:100%;box-sizing:border-box;min-height:90px;padding:12px;border:1px solid #b7aa98;margin:10px 0}.buttons{display:flex;gap:10px;flex-wrap:wrap}.buttons button{border:0;padding:13px 18px;color:white;font-weight:900;cursor:pointer}.approve{background:#28734a}.reject{background:#aa3e35}.hold{background:#80600d}.message{margin-top:15px;color:#efb078}.empty{padding:30px;border:1px solid #363b34;color:#9fa49c}
    @media(max-width:1000px){.reviews-grid{grid-template-columns:1fr}.review-list{max-height:none}.metrics,.checks{grid-template-columns:1fr 1fr}.reviews-head{display:block}}@media(max-width:620px){.metrics,.checks{grid-template-columns:1fr}.detail{padding:20px}.buttons button{width:100%}.passage-review{grid-template-columns:1fr auto}}
  `}</style><div className="reviews-shell"><section className="reviews-head"><div><p className="kicker">Legends Core · Exceções</p><h1>Fila de revisões</h1></div><p>Analise somente os casos que não foram resolvidos automaticamente ou que receberam solicitação do atleta.</p></section><div className="filters">{[["review","Em revisão"],["rejected","Rejeitadas"],["validated","Homologadas"],["all","Todas"]].map(([value,label])=><button className={filter===value?"active":""} key={value} onClick={()=>setFilter(value)}>{label} ({value==="all"?items.length:items.filter(item=>item.status===value).length})</button>)}</div>
  <section className="reviews-grid"><aside className="review-list">{filtered.length?filtered.map(item=><button key={item.id} className={`review-item ${selectedId===item.id?"active":""}`} onClick={()=>setSelectedId(item.id)}><strong>{item.athlete?.full_name??"Atleta"}</strong><span>{item.stage?.name??"Etapa"} · {item.activity?.name??"Atividade"}</span><span>Cobertura {item.coverage_percent??"—"}% · CP {item.checkpoints_passed??0}/{item.checkpoints_total??0}</span><span className="status-pill">{labels[item.status]??item.status}</span></button>):<div className="empty">Nenhum item neste filtro.</div>}</aside>
  <article className="detail">{!selected?<p>Selecione uma atividade para analisar.</p>:<><p className="kicker">{labels[selected.status]??selected.status}</p><h2>{selected.athlete?.full_name??"Atleta"}</h2><p className="detail-sub">{selected.stage?.name} · {selected.stage?.route_label} · {selected.activity?.name}</p><div className="metrics"><div><small>COBERTURA</small><strong>{selected.coverage_percent??"—"}%</strong></div><div><small>CHECKPOINTS</small><strong>{selected.checkpoints_passed??0}/{selected.checkpoints_total??0}</strong></div><div><small>DISTÂNCIA</small><strong>{selected.activity?.distance_km??"—"} km</strong></div><div><small>ELEVAÇÃO</small><strong>{selected.activity?.elevation_m??"—"} m+</strong></div></div><div className="checks"><div className="check">Largada: <strong>{selected.start_ok?"✓":"✕"}</strong></div><div className="check">Chegada: <strong>{selected.finish_ok?"✓":"✕"}</strong></div><div className="check">Sentido: <strong>{selected.direction_ok?"✓":"✕"}</strong></div></div>{selected.route?.route_points?.length&&selected.activity?.gps_points?.length?<ValidationMap officialPoints={selected.route.route_points} activityPoints={selected.activity.gps_points} checkpoints={selected.checkpoints} toleranceM={120}/>:null}
  {(selected.passages?.length||selected.segment_results?.length)?<section className="timing-review"><h3>Passagens e segmentos</h3>{selected.passages?.map((passage)=>{const checkpoint:any=checkpointById.get(passage.checkpoint_id);return <div className="passage-review" key={passage.id}><strong>{checkpoint?.label??"Checkpoint"}</strong><span>{formatPassage(passage.passed_at)}</span><span>{formatDuration(passage.elapsed_s)}</span></div>})}{selected.segment_results?.map((result)=><div className="segment-review" key={result.id}><div><strong>{result.segment?.name??"Segmento"}</strong><span>{result.segment?.segment_type==="climb"?"Subida":result.segment?.segment_type==="sprint"?"Sprint":"Trecho especial"}</span></div><b>{formatDuration(result.elapsed_s)}</b></div>)}</section>:null}
  <h3>Histórico e observações</h3><div className="notes">{selected.notes||"Sem observações."}</div><div className="decision"><strong>Decisão da organização</strong><textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="Registre o motivo da decisão ou uma orientação ao atleta."/><div className="buttons"><button className="approve" disabled={saving} onClick={()=>decide("validated")}>APROVAR</button><button className="reject" disabled={saving} onClick={()=>decide("rejected")}>REJEITAR</button><button className="hold" disabled={saving} onClick={()=>decide("review")}>MANTER EM REVISÃO</button></div></div></>}</article></section>{message?<p className="message">{message}</p>:null}</div></main>;
}
