import KitCarousel from "./KitCarousel";

const metrics = [
  ["04", "dias"],
  ["370,3", "quilômetros"],
  ["6.302", "metros de ascensão"],
  ["100", "vagas"],
];

const stages = [
  { n: "STAGE 01", city: "Canela", stats: "111,9 km · 1.684 m+", route: "/stage-route-1.png", href: "/percursos/stage-1" },
  { n: "STAGE 02", city: "São Francisco de Paula", stats: "89,1 km · 1.520 m+", route: "/stage-route-2.png", href: "/percursos/stage-2" },
  { n: "STAGE 03", city: "Gramado", stats: "99,3 km · 1.522 m+", route: "/stage-route-3.png", href: "/percursos/stage-3" },
  { n: "STAGE 04", city: "Nova Petrópolis", stats: "70,0 km · 1.576 m+", route: "/stage-route-4.png", href: "/percursos/stage-4" },
];

const destinations = [
  { name: "CANELA", icon: "/city-icon-canela.png", href: "https://canela.com.br/" },
  { name: "SÃO FRANCISCO\nDE PAULA", icon: "/city-icon-sao-francisco.png", href: "https://www.saofranciscodepaula.rs.gov.br/portal/turismo" },
  { name: "GRAMADO", icon: "/city-icon-gramado.png", href: "https://www.gramadoinesquecivel.tur.br/" },
  { name: "NOVA\nPETRÓPOLIS", icon: "/city-icon-nova-petropolis.png", href: "https://turismo.novapetropolis.rs.gov.br/" },
];

const differences = [
  ["01", "Autonavegação", "Você recebe os arquivos GPX e percorre cada etapa usando GPS, com autonomia, leitura de percurso e estratégia."],
  ["02", "Bagagem transportada", "A organização leva sua bag de 50 litros entre as cidades-base. Você pedala apenas com o necessário para o dia."],
  ["03", "Hospedagens adaptadas", "Hotéis oficiais e opções indicadas para facilitar check-in, guarda da bike, recuperação e deslocamentos."],
  ["04", "Estrutura pós-etapa", "Bike wash, suporte mecânico, briefing e serviços opcionais de recuperação ao final de cada dia."],
];

const raceEngineFeatures = [
  ["⌁", "Percurso validado", "A atividade é comparada com a rota oficial de cada etapa."],
  ["◎", "Checkpoints digitais", "As passagens mostram a evolução do participante no percurso."],
  ["◷", "Tempo por passagem", "Tempos intermediários e tempo oficial ficam registrados."],
  ["✓", "Apuração transparente", "Revisões e penalidades apresentam decisão e motivo."],
  ["≡", "Classificação automática", "A Gravel Race recebe pontos por etapa, categoria e geral."],
  ["↗", "Resultado ao vivo", "O público acompanha resultados oficiais em uma página própria."],
];

const supportGroups = [
  ["Logística", "Transporte da bagagem", "Hidratação nos checkpoints", "Medalha de conclusão"],
  ["Segurança", "Seguro básico", "Equipe oficial de apoio"],
  ["Percurso", "GPX oficial", "Checkpoints de controle"],
  ["Pós-etapa", "Bike wash", "Mecânica básica"],
];

const safety = [
  ["SPOT", "Rastreamento satelital durante as etapas."],
  ["STARLINK", "Comunicação entre os veículos oficiais de apoio."],
  ["RESGATE", "Ambulância, equipes de resgate e veículos de segurança."],
  ["SEM APOIO EXTERNO", "A assistência é centralizada pela organização para preservar igualdade e segurança."],
];

const faqs = [
  ["É uma prova para iniciantes?", "Não. Não é necessário ser profissional, mas o participante deve estar treinado para quatro dias consecutivos, distância elevada e aproximadamente 1.500 metros de ascensão por etapa."],
  ["Posso participar com MTB ou E-bike?", "Sim, no modo Experience. MTB e E-bike realizam a jornada sem classificação, registro competitivo ou premiação."],
  ["Como funciona a navegação?", "O GPX será disponibilizado no site uma semana antes do evento. É obrigatório usar GPS com navegação e autonomia mínima de 15 horas."],
  ["O que acontece se eu errar o percurso?", "O atleta deve retornar ao ponto em que deixou o trajeto oficial e seguir novamente pelo percurso correto, evitando desclassificação."],
  ["A organização transporta minha bagagem?", "Sim. Cada participante recebe uma bag de 50 litros, transportada entre as cidades-base pela organização."],
  ["Hospedagem e alimentação estão incluídas?", "Não. A organização oferecerá hotéis oficiais, opções adaptadas e jantares opcionais contratados separadamente."],
];

function Logo({ className = "" }: { className?: string }) {
  return <img className={`officialLogo ${className}`} src="/legends-logo-official.png" alt="Legends Bike Race" />;
}

export default function Home() {
  return (
    <main className="redesign">
      <style>{`
        .redesign{--paper:#f4f0db;--ink:#0b0d0c;--copper:#c67a3b;--line:rgba(198,122,59,.34)}
        .redesign .wide{width:min(1440px,calc(100% - 96px));margin-inline:auto}
        .redesign .kicker{text-transform:uppercase;letter-spacing:.24em;color:var(--copper);font:600 14px 'Barlow Condensed';margin:0 0 18px}
        .redesign h2{font:700 clamp(48px,5.7vw,88px) 'Barlow Condensed';text-transform:uppercase;line-height:.9;letter-spacing:-.02em;margin:0}
        .redesign h2 em{font-style:normal;color:var(--copper)}
        .redesign .sectionHead{display:grid;grid-template-columns:1.4fr .8fr;gap:80px;align-items:end;margin-bottom:70px}
        .redesign .sectionHead p{font-size:18px;line-height:1.75;color:#9ba097;margin:0}
        .heroRedesign{min-height:100svh;background:linear-gradient(90deg,rgba(6,8,7,.98),rgba(6,8,7,.77) 38%,rgba(6,8,7,.14) 72%),linear-gradient(0deg,rgba(6,8,7,.92),transparent 44%),url('/hero-production.jpg') center/cover;display:grid;grid-template-rows:104px 1fr auto;color:#f1ece3}
        .heroRedesign .nav{border-bottom:1px solid rgba(241,236,227,.12)}
        .heroRedesign .navCta{display:inline-flex;align-items:center;justify-content:center;background:var(--copper);border:0;color:#fff;padding:11px 17px;font-size:13px;letter-spacing:.09em;white-space:nowrap}
        .heroRedesign .navCta:hover{background:#df8b45;color:#fff}
        .heroMain{display:flex;align-items:center;padding:70px 0}.heroCopy{max-width:790px}
        .heroCopy h1{font:700 clamp(64px,7.2vw,116px) 'Barlow Condensed';text-transform:uppercase;line-height:.84;margin:18px 0 28px}
        .heroIntro{font-size:20px;line-height:1.55;color:#ddd5c9;max-width:680px}.heroCtas{display:flex;gap:20px;align-items:center;margin-top:34px;flex-wrap:wrap}
        .secondaryCta{padding:17px 24px;border:1px solid rgba(241,236,227,.35);text-transform:uppercase;letter-spacing:.1em;font:600 14px 'Barlow Condensed'}
        .heroStats{display:grid;grid-template-columns:repeat(4,1fr);background:rgba(11,13,12,.88);border:1px solid var(--line);backdrop-filter:blur(12px)}
        .heroStat{padding:22px 28px;border-right:1px solid var(--line)}.heroStat:last-child{border:0}.heroStat strong{display:block;font:700 48px 'Barlow Condensed'}.heroStat span{text-transform:uppercase;letter-spacing:.12em;color:#b8b0a4;font:500 12px 'Barlow Condensed'}

        .manifestoRedesign{background:var(--paper);color:var(--ink);padding:110px 0}
        .manifestoFeature{min-height:auto;background:none;overflow:visible}
        .manifestoContent{width:100%;padding:0}
        .manifestoQuote{font:700 clamp(30px,3.35vw,54px) 'Barlow Condensed';text-transform:uppercase;line-height:1.08;max-width:none;margin:0}.manifestoQuote em{font-style:normal;color:var(--copper)}
        .manifestoButton{display:flex;align-items:center;justify-content:space-between;gap:24px;width:min(100%,560px);margin-top:42px;padding:22px 28px;background:var(--copper);color:#111;font:700 18px 'Barlow Condensed';letter-spacing:.08em;text-transform:uppercase}.manifestoButton span:last-child{font-size:28px}
        .manifestoHighlights{display:grid;grid-template-columns:repeat(4,1fr);width:100%;margin-top:72px;border-top:1px solid rgba(17,17,17,.22)}
        .manifestoHighlights span{padding:24px 24px 0 0;border-right:1px solid rgba(17,17,17,.2);font:700 15px 'Barlow Condensed';line-height:1.25;text-transform:uppercase;letter-spacing:.05em}.manifestoHighlights span:not(:first-child){padding-left:24px}.manifestoHighlights span:last-child{border-right:0}

        .factsBand{background:#111411;color:#f1ece3;padding:120px 0}.factsGrid{display:grid;grid-template-columns:repeat(4,1fr);border-top:1px solid var(--line);border-bottom:1px solid var(--line)}
        .fact{padding:34px 28px;border-right:1px solid var(--line)}.fact:last-child{border:0}.fact span{color:var(--copper);font:600 13px 'Barlow Condensed';letter-spacing:.16em}.fact h3{font:700 31px 'Barlow Condensed';text-transform:uppercase;margin:38px 0 16px}.fact p{color:#989e95;line-height:1.65;margin:0}
        .engineHome{padding:112px 0;background:#080a09;color:#f1ece3;border-top:1px solid var(--line);border-bottom:1px solid var(--line)}
        .engineHomeHead{display:grid;grid-template-columns:1.15fr .85fr;gap:70px;align-items:end;margin-bottom:48px}.engineHomeHead p:last-child{color:#a3a89f;font-size:17px;line-height:1.7;margin:0}.engineHome h2{font-size:clamp(48px,5vw,78px)}
        .engineFlow{display:grid;grid-template-columns:repeat(5,1fr);margin-bottom:28px;border:1px solid var(--line)}.engineFlow span{position:relative;padding:19px 15px;text-align:center;color:#d7d1c8;font:700 14px 'Barlow Condensed';letter-spacing:.09em;text-transform:uppercase;border-right:1px solid var(--line)}.engineFlow span:last-child{border:0}.engineFlow span:not(:last-child):after{content:'›';position:absolute;right:-7px;z-index:2;color:var(--copper);background:#080a09;padding:0 2px;font-size:23px;line-height:16px}
        .engineCards{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid var(--line);border-left:1px solid var(--line)}.engineCard{min-height:190px;padding:27px;border-right:1px solid var(--line);border-bottom:1px solid var(--line)}.engineIcon{display:grid;place-items:center;width:35px;height:35px;border:1px solid var(--copper);color:var(--copper);font-size:18px}.engineCard h3{margin:25px 0 9px;font:700 25px 'Barlow Condensed';text-transform:uppercase}.engineCard p{margin:0;color:#969c93;font-size:14px;line-height:1.6}.engineHomeBottom{display:grid;grid-template-columns:1fr auto;gap:28px;align-items:center;margin-top:32px}.engineModes{display:flex;gap:25px;flex-wrap:wrap;color:#b9beb6;font-size:14px}.engineModes strong{color:#f1ece3}.engineLink{display:inline-flex;align-items:center;gap:35px;padding:18px 23px;background:var(--copper);color:#fff;font:700 15px 'Barlow Condensed';letter-spacing:.08em;text-transform:uppercase}
        .modes{background:var(--paper);color:var(--ink);padding:140px 0}.modeGrid{display:grid;grid-template-columns:1fr 1fr;gap:24px}.modeCard{padding:48px;border:1px solid #bdb4a7;background:#ede6d9}.modeCard.dark{background:#101310;color:#f1ece3;border-color:#101310}.modeCard .tag{color:var(--copper);text-transform:uppercase;letter-spacing:.16em;font:600 13px 'Barlow Condensed'}.modeCard h3{font:700 48px 'Barlow Condensed';text-transform:uppercase;margin:22px 0}.modeCard p{line-height:1.75;color:#555950}.modeCard.dark p{color:#a5aaa1}.modeCard ul{list-style:none;padding:0;margin:28px 0 0;display:grid;gap:12px}.modeCard li:before{content:'→';color:var(--copper);margin-right:12px}
        .routePreview{position:relative;overflow:hidden;background-color:#0d0f0e;background-image:linear-gradient(rgba(13,15,14,.9),rgba(13,15,14,.9)),url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='900' height='600' viewBox='0 0 900 600'%3E%3Cg fill='none' stroke='%23c67a3b' stroke-opacity='.22' stroke-width='1.15'%3E%3Cpath d='M-60 90C90 10 180 170 330 86S600 5 760 98 990 88 980-40'/%3E%3Cpath d='M-70 125C95 38 188 198 345 117S610 34 775 127 1010 116 990-10'/%3E%3Cpath d='M-70 160C100 70 200 228 360 147S625 66 790 158 1018 149 1000 25'/%3E%3Cpath d='M-50 470C105 390 210 550 365 465S640 382 805 475 1010 458 990 340'/%3E%3Cpath d='M-60 505C110 420 220 580 380 495S655 415 820 505 1020 492 1000 375'/%3E%3Cellipse cx='690' cy='265' rx='170' ry='112'/%3E%3Cellipse cx='690' cy='265' rx='140' ry='88'/%3E%3Cellipse cx='690' cy='265' rx='105' ry='62'/%3E%3Cellipse cx='155' cy='305' rx='130' ry='90'/%3E%3Cellipse cx='155' cy='305' rx='96' ry='62'/%3E%3C/g%3E%3C/svg%3E");background-size:auto,900px 600px;color:#f1ece3;padding:118px 0}.routePreview .sectionHead{grid-template-columns:1.08fr .92fr;align-items:center;margin-bottom:52px}.routePreview .sectionHead>p{color:#d5cfc5}.routePreview .sectionHead>p strong{color:#f1ece3}.routeSummary{display:grid;grid-template-columns:repeat(3,1fr);border:1px solid var(--line);background:rgba(11,13,12,.82);backdrop-filter:blur(10px)}.routeSummary span{padding:22px 20px;border-right:1px solid var(--line);text-align:center;color:#f1ece3;font:700 25px 'Barlow Condensed';letter-spacing:.04em;text-transform:uppercase}.routeSummary span:last-child{border-right:0}.routeSummary small{display:block;margin-top:5px;color:var(--copper);font-size:10px;letter-spacing:.13em}.stageGridNew{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid var(--line);background:rgba(10,12,11,.78);backdrop-filter:blur(8px)}.stageNew{padding:28px 24px;min-height:445px;border-right:1px solid var(--line);display:flex;flex-direction:column;justify-content:space-between;transition:.25s}.stageNew:last-child{border:0}.stageNew:hover{z-index:2;background:rgba(40,25,15,.86);box-shadow:inset 0 0 0 1px var(--copper),0 0 34px rgba(198,122,59,.16);transform:translateY(-5px)}.stageNew small{color:var(--copper);letter-spacing:.15em;font:600 13px 'Barlow Condensed'}.stageNew img{width:100%;height:180px;object-fit:contain;opacity:.88;filter:sepia(1) saturate(3.4) hue-rotate(338deg) brightness(1.08)}.stageNew h3{font:700 34px 'Barlow Condensed';text-transform:uppercase;line-height:.95;margin:0 0 12px}.stageNew p{color:#d2ccc2;font:600 13px 'Barlow Condensed';letter-spacing:.08em;text-transform:uppercase;margin:0}
        .destinationStory{background:var(--paper);color:var(--ink);padding:140px 0}.destinationText{display:grid;grid-template-columns:1.4fr .8fr;gap:80px}.destinationText p{font-size:18px;line-height:1.8;color:#4d504a}.cityStrip{display:grid;grid-template-columns:repeat(4,1fr);margin-top:70px;border-top:1px solid #bdb4a7}.cityStrip a{padding:30px 20px 0 0;min-height:150px;border-right:1px solid #bdb4a7}.cityStrip a:last-child{border:0;padding-left:22px}.cityStrip strong{font:700 34px 'Barlow Condensed';text-transform:uppercase;line-height:.95}.cityStrip span{display:block;color:var(--copper);margin-top:16px;font-size:13px;text-transform:uppercase;letter-spacing:.1em}
        .includedSection{background:#101310;color:#f1ece3;padding:92px 0}.kitCompactHead{display:flex;align-items:end;justify-content:space-between;gap:50px;margin-bottom:30px}.kitCompactHead .kicker{margin-bottom:10px}.kitCompactHead h2{font-size:clamp(42px,4.2vw,66px)}.kitCompactHead>p{max-width:470px;margin:0 0 5px;color:#9ca198;font-size:16px;line-height:1.6}.kitCarousel{position:relative}.kitCarouselControls{display:flex;justify-content:flex-end;gap:10px;margin-bottom:14px}.kitCarouselControls button{width:48px;height:48px;border:1px solid var(--line);background:#171a17;color:var(--copper);font-size:23px;cursor:pointer;transition:.2s}.kitCarouselControls button:hover{background:var(--copper);color:#101310}.kitCarouselViewport{overflow-x:auto;scroll-snap-type:x mandatory;scrollbar-width:none}.kitCarouselViewport::-webkit-scrollbar{display:none}.kitDetailTrack{display:flex;gap:14px}.kitDetailCard{flex:0 0 calc((100% - 28px)/3);margin:0;overflow:hidden;border:1px solid var(--line);background:#171a17;scroll-snap-align:start}.kitDetailMedia{height:clamp(280px,28vw,400px);display:flex;align-items:center;justify-content:center;padding:22px;background:radial-gradient(circle at 50% 48%,rgba(198,122,59,.12),transparent 62%),#111410}.kitDetailProduct{display:block;width:100%;height:100%;object-fit:contain;filter:drop-shadow(0 18px 24px rgba(0,0,0,.3))}.kitDetailCard figcaption{display:flex;justify-content:space-between;gap:18px;align-items:baseline;padding:18px 20px 20px;border-top:1px solid var(--line)}.kitDetailCard strong{color:#f1ece3;font:700 21px/1 'Barlow Condensed';letter-spacing:.04em;text-transform:uppercase}.kitDetailCard figcaption span{color:#8f958c;font-size:13px;text-align:right}.supportStrip{display:grid;grid-template-columns:repeat(4,1fr);margin-top:22px;border:1px solid var(--line)}.supportGroup{padding:20px 22px;border-right:1px solid var(--line)}.supportGroup:last-child{border-right:0}.supportGroup h3{margin:0 0 13px;color:var(--copper);font:700 17px 'Barlow Condensed';letter-spacing:.1em;text-transform:uppercase}.supportGroup ul{list-style:none;margin:0;padding:0;display:grid;gap:7px}.supportGroup li{color:#b8bdb5;font-size:13px;line-height:1.35}.supportGroup li:before{content:'✓';margin-right:8px;color:var(--copper)}
        .safetySection{background:#0b0d0c;color:#f1ece3;padding:120px 0}.safetyGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:20px}.safetyCard{border:1px solid var(--line);padding:30px}.safetyCard h3{font:700 26px 'Barlow Condensed';color:var(--copper);margin:0 0 14px}.safetyCard p{color:#9ca198;line-height:1.6;margin:0}
        .profileSection{background:var(--paper);color:var(--ink);padding:140px 0}.profileBox{display:grid;grid-template-columns:1fr 1fr;gap:70px;align-items:center}.profileBox blockquote{font:700 clamp(42px,5vw,72px) 'Barlow Condensed';text-transform:uppercase;line-height:.92;margin:0}.profileBox blockquote em{font-style:normal;color:var(--copper)}.profileBox ul{list-style:none;padding:0;margin:0;display:grid;gap:18px}.profileBox li{border-bottom:1px solid #bdb4a7;padding-bottom:18px;font-size:17px;line-height:1.6}
        .faqSection{background:#121411;color:#f1ece3;padding:140px 0}.faqList{border-top:1px solid var(--line)}.faqList details{border-bottom:1px solid var(--line);padding:24px 0}.faqList summary{cursor:pointer;font:600 24px 'Barlow Condensed';text-transform:uppercase;list-style:none}.faqList summary:after{content:'+';float:right;color:var(--copper)}.faqList details[open] summary:after{content:'–'}.faqList p{max-width:850px;color:#a9aea6;line-height:1.75}
        .priorityCta{padding:160px 0;text-align:center;color:#f1ece3;background:linear-gradient(rgba(7,9,8,.75),rgba(7,9,8,.95)),url('/hero-production.jpg') center/cover}.priorityCta h2{max-width:1000px;margin:0 auto}.priorityCta p{color:#b8bdb5;max-width:680px;margin:28px auto 34px;line-height:1.7}.priorityCta .button{min-width:280px}
        @media(max-width:1000px){.redesign .wide{width:min(100% - 48px,920px)}.redesign .sectionHead,.destinationText,.profileBox,.engineHomeHead{grid-template-columns:1fr}.manifestoQuote{font-size:clamp(30px,5vw,46px)}.factsGrid,.safetyGrid,.stageGridNew{grid-template-columns:1fr 1fr}.modeGrid{grid-template-columns:1fr}.supportStrip{grid-template-columns:1fr 1fr}.supportGroup:nth-child(2){border-right:0}.supportGroup:nth-child(-n+2){border-bottom:1px solid var(--line)}.engineCards{grid-template-columns:1fr 1fr}}
        @media(max-width:640px){.redesign .wide{width:calc(100% - 32px)}.heroRedesign{grid-template-rows:82px 1fr auto;min-height:100svh;background-position:68% center}.heroRedesign .navCta{display:inline-flex;padding:9px 11px;font-size:10px;letter-spacing:.06em}.heroMain{padding:44px 0}.heroCopy h1{font-size:56px}.heroIntro{font-size:16px}.heroStats{grid-template-columns:1fr 1fr}.heroStat:nth-child(2){border-right:0}.heroStat:nth-child(-n+2){border-bottom:1px solid var(--line)}.heroStat strong{font-size:38px}.manifestoRedesign,.factsBand,.modes,.daySection,.routePreview,.destinationStory,.includedSection,.safetySection,.profileSection,.faqSection,.engineHome{padding:68px 0}.manifestoQuote{font-size:30px;line-height:1.04}.manifestoButton{font-size:16px;padding:18px 20px;margin-top:30px}.manifestoHighlights{grid-template-columns:1fr 1fr;margin-top:48px}.manifestoHighlights span{border-bottom:1px solid rgba(17,17,17,.2);padding:18px 10px 18px 0}.manifestoHighlights span:not(:first-child){padding-left:10px}.factsGrid,.stageGridNew,.safetyGrid,.cityStrip,.engineCards{grid-template-columns:1fr}.fact,.stageNew,.safetyCard,.cityStrip a{border-right:0;border-bottom:1px solid var(--line)}.modeCard{padding:34px 26px}.daySection{padding:64px 0}.daySection .sectionHead{margin-bottom:30px}.timelineItem{grid-template-columns:32px 76px 1fr;gap:12px;padding:13px 0}.timelineIcon{width:28px;height:28px;font-size:14px}.timelineItem strong{font-size:19px}.timelineItem span:last-child{font-size:14px}.stageNew{min-height:330px}.destinationText{gap:20px}.cityStrip a:last-child{padding-left:0}.kitCompactHead{display:block;margin-bottom:24px}.kitCompactHead h2{font-size:42px}.kitCompactHead>p{margin-top:15px}.kitDetailCard{flex-basis:100%}.kitDetailMedia{height:300px;padding:18px}.supportStrip{grid-template-columns:1fr 1fr}.supportGroup{padding:17px 15px}.supportGroup h3{font-size:15px}.supportGroup li{font-size:12px}.profileBox{gap:34px}.engineHomeHead{gap:22px;margin-bottom:34px}.engineFlow{grid-template-columns:1fr}.engineFlow span{border-right:0;border-bottom:1px solid var(--line);padding:13px}.engineFlow span:last-child{border:0}.engineFlow span:not(:last-child):after{content:'⌄';right:auto;bottom:-8px;left:calc(50% - 7px)}.engineCard{min-height:0}.engineHomeBottom{grid-template-columns:1fr}.engineModes{display:grid;gap:10px}.engineLink{justify-content:space-between}}
        @media(max-width:800px){.routePreview .sectionHead{grid-template-columns:1fr;gap:28px}.routeSummary{grid-template-columns:1fr}.routeSummary span{padding:15px;border-right:0;border-bottom:1px solid var(--line)}.routeSummary span:last-child{border-bottom:0}.routePreview{padding:76px 0}.stageNew img{height:155px}}
        /* Mantém a apresentação escura mesmo diante das regras legadas globais. */
        .redesign .routePreview{background:#0d0f0e linear-gradient(rgba(13,15,14,.9),rgba(13,15,14,.9)) url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='900' height='600' viewBox='0 0 900 600'%3E%3Cg fill='none' stroke='%23c67a3b' stroke-opacity='.22' stroke-width='1.15'%3E%3Cpath d='M-60 90C90 10 180 170 330 86S600 5 760 98 990 88 980-40'/%3E%3Cpath d='M-70 125C95 38 188 198 345 117S610 34 775 127 1010 116 990-10'/%3E%3Cpath d='M-70 160C100 70 200 228 360 147S625 66 790 158 1018 149 1000 25'/%3E%3Cpath d='M-50 470C105 390 210 550 365 465S640 382 805 475 1010 458 990 340'/%3E%3Cpath d='M-60 505C110 420 220 580 380 495S655 415 820 505 1020 492 1000 375'/%3E%3Cellipse cx='690' cy='265' rx='170' ry='112'/%3E%3Cellipse cx='690' cy='265' rx='140' ry='88'/%3E%3Cellipse cx='690' cy='265' rx='105' ry='62'/%3E%3Cellipse cx='155' cy='305' rx='130' ry='90'/%3E%3Cellipse cx='155' cy='305' rx='96' ry='62'/%3E%3C/g%3E%3C/svg%3E") !important;background-size:auto,900px 600px !important;color:#f1ece3 !important}.redesign .routePreview .sectionHead h2,.redesign .routePreview .stageNew h3{color:#f1ece3 !important}.redesign .routePreview .sectionHead>p{color:#d5cfc5 !important}.redesign .routePreview .stageGridNew{background:rgba(10,12,11,.78) !important;border-color:var(--line) !important}.redesign .routePreview .stageNew{background:transparent !important;border-color:var(--line) !important}.redesign .routePreview .stageNew p{color:#d2ccc2 !important}.redesign .routePreview .stageNew:hover{background:rgba(40,25,15,.86) !important}
        .redesign .routePreview{background-color:#0d0f0e !important;background-image:repeating-radial-gradient(ellipse at 82% 34%,transparent 0 38px,rgba(198,122,59,.19) 39px 40px,transparent 41px 59px),repeating-radial-gradient(ellipse at 14% 66%,transparent 0 32px,rgba(198,122,59,.15) 33px 34px,transparent 35px 51px),linear-gradient(rgba(13,15,14,.94),rgba(13,15,14,.94)) !important;background-size:900px 620px,720px 520px,auto !important}
      `}</style>

      <section className="heroRedesign" id="inicio">
        <nav className="nav wide" aria-label="Navegação principal">
          <a className="brand" href="#inicio"><Logo /></a>
          <div className="navLinks"><a href="/a-prova">A prova</a><a href="/#percurso">Percursos</a><a href="#modalidades">Modalidades</a><a href="/race-engine">Race Engine</a><a href="#faq">FAQ</a></div>
          <a className="navCta" href="/acesso">Atleta / Organizador</a>
        </nav>
        <div className="heroMain wide"><div className="heroCopy"><p className="kicker">Serra Gaúcha · Brasil</p><h1>Onde o asfalto termina, a diversão começa.</h1><p className="heroIntro"><strong>Uma Stage Race Premium de Gravel pela Serra Gaúcha.</strong><br />Quatro etapas, quatro cidades e uma travessia criada para quem procura muito mais do que uma prova.</p><div className="heroCtas"><a className="button" href="/a-prova">Conheça a Legends <span>→</span></a><a className="secondaryCta" href="/lista-prioritaria">Entre para a lista prioritária</a></div></div></div>
        <div className="wide"><div className="heroStats">{metrics.map(([value,label]) => <div className="heroStat" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></div>
      </section>

      <section className="manifestoRedesign" id="conceito"><div className="wide manifestoFeature">
        <div className="manifestoContent">
          <p className="kicker">Por que ela existe</p>
          <h2 className="manifestoQuote">A Legends não foi criada para quem procura apenas uma medalha. Foi criada para quem acredita que a bicicleta é o melhor passaporte para <em>descobrir lugares, pessoas e histórias.</em></h2>
          <a className="manifestoButton" href="/a-prova"><span>Entenda como funciona a Legends</span><span>→</span></a>
        </div>
        <figure className="manifestoKitVisual">
          <img src="/kit-legends-ultimate.webp" alt="Kit oficial da prova Legends Ultimate com vestuário e acessórios" />
          <figcaption>Kit oficial Legends Ultimate</figcaption>
        </figure>
      </div></section>

      <section className="routePreview" id="percurso"><div className="wide"><div className="sectionHead"><div><p className="kicker">Quatro etapas</p><h2>Uma história contínua.<br /><em>Quatro destinos.</em></h2></div><div className="routeSummary"><span>370,3 km<small>Distância total</small></span><span>6.302 m+<small>Ascensão total</small></span><span>≈ 75%<small>Não pavimentado</small></span></div></div><div className="stageGridNew">{stages.map(stage => <a className="stageNew" href={stage.href} key={stage.n}><small>{stage.n}</small><img src={stage.route} alt="" /><div><h3>{stage.city}</h3><p>{stage.stats}</p></div></a>)}</div></div></section>

      <section className="modes" id="modalidades"><div className="wide"><div className="sectionHead"><div><p className="kicker">Escolha como viver a Legends</p><h2>Competir ou experimentar.<br /><em>A jornada é a mesma.</em></h2></div><p>O participante escolhe o propósito: disputar a classificação no gravel ou realizar a travessia em modo turismo.</p></div><div className="modeGrid"><div className="modeCard dark"><span className="tag">Modalidade competitiva</span><h3>Legends Gravel Race</h3><p>Para ciclistas de gravel ou cyclocross que desejam disputar as quatro etapas com tempo registrado, classificação por pontos, categorias e premiação final.</p><ul><li>Classificação oficial</li><li>Pontuação por etapa</li><li>Categorias por idade</li><li>Troféus ao final da travessia</li></ul></div><div className="modeCard"><span className="tag">Modalidade turismo</span><h3>Legends Experience</h3><p>Para participantes de MTB e E-bike que desejam viver o mesmo percurso e a mesma estrutura, sem pressão por tempo, ranking ou resultado competitivo.</p><ul><li>Sem classificação</li><li>MTB e E-bike permitidas</li><li>Mesma logística e segurança</li><li>Foco em turismo e desafio pessoal</li></ul></div></div></div></section>
      <section className="factsBand"><div className="wide"><div className="sectionHead"><div><p className="kicker">O que torna a Legends diferente</p><h2>Aventura com estrutura.<br /><em>Autonomia com cuidado.</em></h2></div><p>Uma experiência pensada para eliminar a complexidade logística sem retirar do atleta o protagonismo da jornada.</p></div><div className="factsGrid">{differences.map(([n,title,text]) => <div className="fact" key={n}><span>{n}</span><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>
      <section className="engineHome" id="race-engine"><div className="wide"><div className="engineHomeHead"><div><p className="kicker">Tecnologia própria · Legends Race Engine</p><h2>Cada quilômetro conta.<br /><em>Cada resultado pode ser comprovado.</em></h2></div><p>Da atividade registrada no GPS à publicação oficial: percurso, passagens, decisões esportivas e resultados reunidos em uma única experiência.</p></div><div className="engineFlow" aria-label="Fluxo do Race Engine"><span>Pedale</span><span>Sincronize</span><span>Valide</span><span>Acompanhe</span><span>Comprove</span></div><div className="engineCards">{raceEngineFeatures.map(([icon,title,text])=><article className="engineCard" key={title}><span className="engineIcon" aria-hidden="true">{icon}</span><h3>{title}</h3><p>{text}</p></article>)}</div><div className="engineHomeBottom"><div className="engineModes"><span><strong>Gravel Race:</strong> tempo, pontos e classificação.</span><span><strong>Experience:</strong> jornada validada para MTB e E-bike, sem ranking competitivo.</span></div><a className="engineLink" href="/race-engine">Conheça o Race Engine <span>→</span></a></div></div></section>
      <section className="destinationStory" id="destino"><div className="wide"><div className="destinationText"><div><p className="kicker">O Brasil que poucos conhecem</p><h2>A Serra não é cenário.<br /><em>Ela faz parte da prova.</em></h2></div><div><p>A Serra Gaúcha reúne estradas rurais, araucárias, vales, cânions, pequenas comunidades, gastronomia reconhecida e cidades marcadas pela imigração europeia. Cada etapa revela um novo território e uma nova forma de conhecer o Brasil sobre duas rodas.</p><p>O ciclista estrangeiro virá à Legends para viver, de gravel, uma travessia premium por um Brasil surpreendente que poucos no mundo conhecem.</p></div></div><div className="destinationNames" id="cidades">{destinations.map(destination => <a href={destination.href} target="_blank" rel="noreferrer" key={destination.name} aria-label={`Conheça ${destination.name.replace("\n", " ")}`}><span className="cityIcon"><img src={destination.icon} alt="" aria-hidden="true" /></span><strong>{destination.name.split("\n").map((line, index) => <span key={line}>{line}{index === 0 && destination.name.includes("\n") ? <br /> : null}</span>)}</strong><i aria-hidden="true">↗</i></a>)}</div></div></section>
      <section className="includedSection"><div className="wide"><div className="kitCompactHead"><div><p className="kicker">Kit e estrutura incluídos</p><h2>Tudo para viver<br /><em>os quatro dias.</em></h2></div><p>Produtos oficiais e suporte de prova reunidos em uma estrutura pensada para você concentrar energia no percurso.</p></div><KitCarousel /><div className="supportStrip">{supportGroups.map(([title,...items]) => <div className="supportGroup" key={title}><h3>{title}</h3><ul>{items.map(item => <li key={item}>{item}</li>)}</ul></div>)}</div></div></section>
      <section className="safetySection"><div className="wide"><div className="sectionHead"><div><p className="kicker">Segurança e suporte</p><h2>Aventura exige liberdade.<br /><em>Confiança exige estrutura.</em></h2></div><p>A operação utiliza comunicação, rastreamento e resgate dimensionados para uma travessia de múltiplos dias.</p></div><div className="safetyGrid">{safety.map(([title,text]) => <div className="safetyCard" key={title}><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>
      <section className="profileSection"><div className="wide profileBox"><blockquote>Não é para iniciantes.<br />Não é para todos.<br /><em>É para quem está pronto.</em></blockquote><ul><li>Entusiastas do ciclismo com mais de 35 anos, tempo para viajar e desejo de descobrir novos destinos.</li><li>Não é necessário ser atleta profissional, mas é indispensável estar treinado para quatro dias consecutivos.</li><li>O participante deve ter autonomia, disciplina e capacidade de administrar esforço, alimentação, equipamento e navegação.</li><li><strong>Not for everyone. Only for Legends.</strong></li></ul></div></section>
      <section className="faqSection" id="faq"><div className="wide"><div className="sectionHead"><div><p className="kicker">Perguntas frequentes</p><h2>Antes de aceitar o desafio,<br /><em>entenda a jornada.</em></h2></div><p>As informações definitivas de data, valores, hotéis e programação serão publicadas após a confirmação oficial da primeira edição.</p></div><div className="faqList">{faqs.map(([q,a]) => <details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section>
      <section className="priorityCta" id="interesse"><div className="wide"><Logo className="ctaLogo" /><p className="kicker">A data ainda será revelada</p><h2>Seja um dos<br /><em>100 Legends.</em></h2><p>Entre para a lista prioritária e receba em primeira mão a data oficial, os valores, os hotéis parceiros e a abertura das inscrições.</p><a className="button" href="/lista-prioritaria">Entrar para a lista prioritária <span>→</span></a></div></section>
      <footer className="footer wide"><Logo className="footerLogo" /><p>Uma experiência Threerace Sports</p><p>Serra Gaúcha · Brasil</p></footer>
    </main>
  );
}
