import type { Metadata } from "next";
import PrintButton from "../PrintButton";

export const metadata: Metadata = { title: "Atestado Médico | Legends Bike Race 2027", robots: { index: false, follow: false } };

export default function AtestadoPage() {
  return <main className="formPage"><style>{`
    .formPage{--copper:#b47049;box-sizing:border-box;width:min(210mm,100%);min-height:297mm;margin:0 auto;padding:12mm 14mm;color:#222;background:#fff;font-family:Arial,sans-serif}.brand{text-align:center;border-bottom:1.5px solid var(--copper);padding-bottom:6mm;margin-bottom:5mm}.brand img{width:34mm;max-height:16mm;object-fit:contain}.brand h1{font:700 20pt 'Barlow Condensed',Arial;text-transform:uppercase;margin:3mm 0 1mm}.brand p{margin:0;color:var(--copper);font-weight:700;font-size:8pt}.intro{text-align:center;color:#666;font-size:8.5pt;margin:0 0 4mm}.section{margin-top:5mm;break-inside:avoid}.section h2{font:700 12pt 'Barlow Condensed',Arial;text-transform:uppercase;color:var(--copper);border-bottom:1px solid #ddd;padding-bottom:1.5mm;margin:0 0 2.5mm}.field{display:grid;grid-template-columns:42mm 1fr;border:1px solid #ddd;border-bottom:0;min-height:8mm;font-size:8.5pt}.field:last-child{border-bottom:1px solid #ddd}.field strong{background:#f1e9de;padding:2.2mm}.field span{padding:2.2mm}.text{line-height:1.42;font-size:9.2pt;margin:2.5mm 0}.choice{margin:2.4mm 0;font-size:9pt;font-weight:700;color:var(--copper)}.recommend{border:1px solid #ddd;padding:2.5mm;margin:2mm 0;color:#555;font-size:8.5pt;min-height:12mm}.signature{text-align:center;margin-top:9mm}.signature div{width:100mm;max-width:100%;margin:0 auto;border-top:1px solid #333;padding-top:2mm;font-size:8.5pt}.note{margin-top:5mm;color:#666;font-size:7.3pt;line-height:1.35}.print{display:block;margin:7mm auto 0;background:var(--copper);color:#fff;border:0;padding:10px 16px;width:max-content;font-weight:700;text-transform:uppercase;font-size:11px;cursor:pointer}@media(max-width:700px){.formPage{width:100%;min-height:auto;padding:24px 18px}.field{grid-template-columns:130px 1fr}.brand h1{font-size:25px}}@media print{html,body{margin:0!important;padding:0!important;background:#fff!important}.print{display:none!important}.formPage{width:182mm!important;height:269mm!important;min-height:269mm!important;margin:0!important;padding:0!important;overflow:hidden!important}.brand{padding-bottom:4mm;margin-bottom:3mm}.brand img{width:31mm}.brand h1{font-size:18pt;margin:2mm 0 1mm}.intro{margin-bottom:3mm}.section{margin-top:3.5mm}.section h2{font-size:11pt;margin-bottom:1.5mm}.field{min-height:6.8mm}.field strong,.field span{padding:1.6mm}.text{font-size:8.7pt;line-height:1.32;margin:1.8mm 0}.choice{margin:1.7mm 0}.recommend{min-height:8mm;padding:1.7mm}.signature{margin-top:6mm}.note{margin-top:3mm;font-size:6.8pt}@page{size:A4 portrait;margin:14mm}}
  `}</style>
  <div className="brand"><img src="/legends-logo-official.png" alt="Legends Bike Race" /><h1>Atestado Médico para Participação</h1><p>LEGENDS BIKE RACE 2027 · 29 ABR — 02 MAI · SERRA GAÚCHA / RS</p></div>
  <p className="intro">Documento obrigatório · Modelo oficial em uma folha A4 · Apresentar acompanhado da Declaração de Saúde enviada online.</p>
  <section className="section"><h2>Dados do participante</h2><div className="field"><strong>Número do atleta</strong><span /></div><div className="field"><strong>Nome completo</strong><span /></div><div className="field"><strong>CPF / Passaporte</strong><span /></div><div className="field"><strong>Data de nascimento</strong><span /></div></section>
  <section className="section"><h2>Atestado</h2><p className="text">Atesto que o(a) participante acima identificado(a) foi submetido(a) a avaliação médica e que, na data deste exame, não foram identificadas contraindicações clínicas aparentes à prática de ciclismo de longa duração e à participação na <strong>Legends Bike Race 2027</strong>, evento de endurance realizado em quatro dias consecutivos, com aproximadamente <strong>370 km e 6.302 m de ganho acumulado de elevação</strong>, incluindo esforço prolongado, trechos pavimentados e não pavimentados, variações climáticas e autonavegação.</p><p className="text"><strong>Com base na avaliação realizada, considero o(a) participante:</strong></p><p className="choice">☐ APTO(A) para participar do evento.</p><p className="choice">☐ APTO(A) COM RECOMENDAÇÕES / RESTRIÇÕES descritas abaixo.</p><div className="recommend">____________________________________________________________________________________<br/><br/>____________________________________________________________________________________</div><p className="choice">☐ NÃO APTO(A) para participar do evento.</p></section>
  <section className="section"><h2>Identificação do médico</h2><div className="field"><strong>Nome do médico</strong><span /></div><div className="field"><strong>CRM / UF</strong><span /></div><div className="field"><strong>RQE, se aplicável</strong><span /></div><div className="field"><strong>Contato profissional</strong><span /></div><div className="field"><strong>Data da avaliação</strong><span /></div></section>
  <div className="signature"><div>Assinatura e carimbo do médico / assinatura eletrônica válida</div></div>
  <p className="note"><strong>ORIENTAÇÃO AO MÉDICO:</strong> emitir após avaliação do paciente, contendo identificação do paciente e do médico, CRM/UF, data e assinatura. Diagnóstico/CID somente deve constar quando houver autorização expressa do paciente.</p>
  <PrintButton />
  </main>;
}
