import type { Metadata } from "next";
import PrintButton from "../PrintButton";

export const metadata: Metadata = { title: "Atestado Médico | Legends Bike Race 2027", robots: { index: false, follow: false } };

export default function AtestadoPage() {
  return <main className="formPage"><style>{`
    .formPage{--copper:#b47049;max-width:900px;margin:0 auto;padding:34px 42px 60px;color:#222;background:#fff;font-family:Arial,sans-serif}.brand{text-align:center;border-bottom:2px solid var(--copper);padding-bottom:14px;margin-bottom:24px}.brand img{width:145px}.brand h1{font:700 28px 'Barlow Condensed',Arial;text-transform:uppercase;margin:12px 0 4px}.brand p{margin:0;color:var(--copper);font-weight:700;font-size:12px}.intro{text-align:center;color:#666;font-size:12px}.section{margin-top:24px}.section h2{font:700 17px 'Barlow Condensed',Arial;text-transform:uppercase;color:var(--copper);border-bottom:1px solid #ddd;padding-bottom:6px}.field{display:grid;grid-template-columns:190px 1fr;border:1px solid #ddd;border-bottom:0;min-height:38px}.field:last-child{border-bottom:1px solid #ddd}.field strong{background:#f1e9de;padding:10px}.field span{padding:10px}.text{line-height:1.65;font-size:14px}.choice{margin:12px 0;font-weight:700;color:var(--copper)}.signature{text-align:center;margin-top:42px}.signature div{width:420px;max-width:100%;margin:0 auto;border-top:1px solid #333;padding-top:7px;font-size:12px}.note{margin-top:28px;color:#666;font-size:10px;line-height:1.5}.print{display:block;margin:25px auto 0;background:var(--copper);color:#fff;border:0;padding:12px 18px;width:max-content;font-weight:700;text-transform:uppercase;font-size:12px;cursor:pointer}@media print{.print{display:none}.formPage{padding:0;max-width:none}@page{margin:14mm}}
  `}</style>
  <div className="brand"><img src="/legends-logo-official.png" alt="Legends Bike Race" /><h1>Atestado Médico para Participação</h1><p>LEGENDS BIKE RACE 2027 · 29 ABR — 02 MAI · SERRA GAÚCHA / RS</p></div>
  <p className="intro">Documento obrigatório. Apresentar juntamente com a Declaração de Saúde.</p>
  <section className="section"><h2>Dados do participante</h2><div className="field"><strong>Nome completo</strong><span /></div><div className="field"><strong>CPF / Passaporte</strong><span /></div><div className="field"><strong>Data de nascimento</strong><span /></div><div className="field"><strong>Telefone</strong><span /></div></section>
  <section className="section"><h2>Atestado</h2><p className="text">Atesto que o(a) participante acima identificado(a) foi submetido(a) a avaliação médica e que, na data deste exame, não foram identificadas contraindicações clínicas aparentes à prática de ciclismo de longa duração e à participação na <strong>Legends Bike Race 2027</strong>, evento de endurance em quatro dias consecutivos, com aproximadamente 370 km e 6.302 m de ganho acumulado, incluindo esforço prolongado, trechos pavimentados e não pavimentados, variações climáticas e autonavegação.</p><p className="text"><strong>Com base na avaliação realizada, considero o(a) participante:</strong></p><p className="choice">☐ APTO(A) para participar do evento.</p><p className="choice">☐ NÃO APTO(A) para participar do evento.</p></section>
  <section className="section"><h2>Identificação do médico</h2><div className="field"><strong>Nome do médico</strong><span /></div><div className="field"><strong>CRM / UF</strong><span /></div><div className="field"><strong>RQE, se aplicável</strong><span /></div><div className="field"><strong>Contato profissional</strong><span /></div><div className="field"><strong>Data da avaliação</strong><span /></div></section>
  <div className="signature"><div>Assinatura e carimbo do médico / assinatura eletrônica válida</div></div>
  <p className="note"><strong>ORIENTAÇÃO AO MÉDICO:</strong> emitir após avaliação do paciente, com identificação do médico e paciente, CRM, data, assinatura e contato profissional. Diagnóstico/CID somente com autorização expressa do paciente.</p>
  <PrintButton />
  </main>;
}
