import type { Metadata } from "next";
import PrintButton from "../PrintButton";

export const metadata: Metadata = { title: "Atestado Médico | Legends Bike Race 2027", robots: { index: false, follow: false } };

export default function AtestadoPage() {
  return <main className="formPage"><style>{`
    .formPage{--copper:#b47049;box-sizing:border-box;width:min(210mm,100%);margin:0 auto;padding:9mm 12mm 10mm;color:#222;background:#fff;font-family:Arial,sans-serif}.brand{text-align:center;border-bottom:1.2px solid var(--copper);padding-bottom:3.5mm;margin-bottom:3.5mm}.brand img{width:29mm;max-height:12mm;object-fit:contain}.brand h1{font:700 17pt 'Barlow Condensed',Arial;text-transform:uppercase;margin:1.8mm 0 .6mm}.brand p{margin:0;color:var(--copper);font-weight:700;font-size:7.2pt}.intro{text-align:center;color:#666;font-size:7.4pt;margin:0 0 2.8mm}.section{margin-top:3mm;break-inside:avoid}.section h2{font:700 10.5pt 'Barlow Condensed',Arial;text-transform:uppercase;color:var(--copper);border-bottom:1px solid #ddd;padding-bottom:1mm;margin:0 0 1.5mm}.field{display:grid;grid-template-columns:39mm 1fr;border:1px solid #ddd;border-bottom:0;min-height:6.4mm;font-size:7.8pt}.field:last-child{border-bottom:1px solid #ddd}.field strong{background:#f1e9de;padding:1.6mm}.field span{padding:1.6mm}.text{line-height:1.27;font-size:8pt;margin:1.5mm 0}.choice{margin:1.35mm 0;font-size:7.9pt;font-weight:700;color:var(--copper)}.recommend{border:1px solid #ddd;padding:1.5mm;margin:1.2mm 0;color:#555;font-size:7.4pt;min-height:7mm}.signature{text-align:center;margin-top:5mm}.signature div{width:92mm;max-width:100%;margin:0 auto;border-top:1px solid #333;padding-top:1.5mm;font-size:7.6pt}.note{margin-top:2.8mm;color:#666;font-size:6.4pt;line-height:1.25}.print{display:block;margin:5mm auto 0;background:var(--copper);color:#fff;border:0;padding:10px 16px;width:max-content;font-weight:700;text-transform:uppercase;font-size:11px;cursor:pointer}@media(max-width:700px){.formPage{width:100%;padding:22px 16px}.field{grid-template-columns:125px 1fr}.brand h1{font-size:24px}}@media print{html,body{margin:0!important;padding:0!important;background:#fff!important}.print{display:none!important}.formPage{width:186mm!important;height:273mm!important;max-height:273mm!important;margin:0!important;padding:0!important;overflow:hidden!important;page-break-after:avoid!important;break-after:avoid-page!important}.brand{padding-bottom:2.8mm;margin-bottom:2.6mm}.brand img{width:27mm;max-height:10mm}.brand h1{font-size:15.5pt;margin:1.3mm 0 .4mm}.brand p{font-size:6.8pt}.intro{font-size:6.8pt;margin-bottom:2.2mm}.section{margin-top:2.4mm;break-inside:avoid-page!important;page-break-inside:avoid!important}.section h2{font-size:9.8pt;margin-bottom:1.1mm;padding-bottom:.8mm}.field{min-height:5.7mm;font-size:7.1pt}.field strong,.field span{padding:1.35mm}.text{font-size:7.35pt;line-height:1.2;margin:1.1mm 0}.choice{font-size:7.2pt;margin:1mm 0}.recommend{min-height:5.5mm;padding:1.1mm;margin:1mm 0;font-size:6.9pt}.signature{margin-top:4mm}.signature div{font-size:7pt;padding-top:1mm}.note{margin-top:2mm;font-size:5.8pt;line-height:1.18}@page{size:A4 portrait;margin:12mm}}
  `}</style>
  <div className="brand"><img src="/legends-logo-official.png" alt="Legends Bike Race" /><h1>Atestado Médico para Participação</h1><p>LEGENDS BIKE RACE 2027 · 29 ABR — 02 MAI · SERRA GAÚCHA / RS</p></div>
  <p className="intro">Documento obrigatório · Modelo oficial em uma única folha A4 · Apresentar acompanhado da Declaração de Saúde enviada online.</p>
  <section className="section"><h2>Dados do participante</h2><div className="field"><strong>Número do atleta</strong><span /></div><div className="field"><strong>Nome completo</strong><span /></div><div className="field"><strong>CPF / Passaporte</strong><span /></div><div className="field"><strong>Data de nascimento</strong><span /></div></section>
  <section className="section"><h2>Atestado</h2><p className="text">Atesto que o(a) participante acima identificado(a) foi submetido(a) a avaliação médica e que, na data deste exame, não foram identificadas contraindicações clínicas aparentes à prática de ciclismo de longa duração e à participação na <strong>Legends Bike Race 2027</strong>, evento de endurance realizado em quatro dias consecutivos, com aproximadamente <strong>370 km e 6.302 m de ganho acumulado de elevação</strong>, incluindo esforço prolongado, trechos pavimentados e não pavimentados, variações climáticas e autonavegação.</p><p className="text"><strong>Com base na avaliação realizada, considero o(a) participante:</strong></p><p className="choice">☐ APTO(A) para participar do evento.</p><p className="choice">☐ APTO(A) COM RECOMENDAÇÕES / RESTRIÇÕES descritas abaixo.</p><div className="recommend">____________________________________________________________________________________<br/>____________________________________________________________________________________</div><p className="choice">☐ NÃO APTO(A) para participar do evento.</p></section>
  <section className="section"><h2>Identificação do médico</h2><div className="field"><strong>Nome do médico</strong><span /></div><div className="field"><strong>CRM / UF</strong><span /></div><div className="field"><strong>RQE, se aplicável</strong><span /></div><div className="field"><strong>Contato profissional</strong><span /></div><div className="field"><strong>Data da avaliação</strong><span /></div></section>
  <div className="signature"><div>Assinatura e carimbo do médico / assinatura eletrônica válida</div></div>
  <p className="note"><strong>ORIENTAÇÃO AO MÉDICO:</strong> emitir após avaliação do paciente, contendo identificação do paciente e do médico, CRM/UF, data e assinatura. Diagnóstico/CID somente deve constar quando houver autorização expressa do paciente.</p>
  <PrintButton />
  </main>;
}
