"use client";

import { useEffect, useState } from "react";

type Summary={total:number;validated:number;review:number;rejected:number;pending:number};
type Item={id:string;status:string;coverage_percent:number|null;athlete?:{full_name?:string};stage?:{name?:string};activity?:{name?:string;created_at?:string}};

export default function OrganizationDashboard(){
  const [summary,setSummary]=useState<Summary|null>(null);const [items,setItems]=useState<Item[]>([]);const [error,setError]=useState("");
  useEffect(()=>{fetch("/api/admin/reviews",{cache:"no-store"}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error);setSummary(p.summary);setItems(p.items??[])}).catch(e=>setError(e.message));},[]);
  const queue=items.filter(item=>item.status==="review").slice(0,5);
  return <main className="org-dashboard"><style>{`
    .org-dashboard{min-height:calc(100vh - 72px);background:#0d100d;color:#f3eee5;padding:46px 4vw 80px;font-family:Arial,sans-serif}.org-kicker{color:#d47b2d;letter-spacing:.2em;text-transform:uppercase;font-size:12px;font-weight:900}.org-hero{display:flex;align-items:end;justify-content:space-between;gap:30px;max-width:1280px;margin:auto}.org-hero h1{font-size:clamp(44px,6vw,76px);line-height:.9;text-transform:uppercase;margin:14px 0}.org-hero p{color:#aeb3ab;max-width:700px;line-height:1.7}.org-content{max-width:1280px;margin:38px auto 0}.org-metrics{display:grid;grid-template-columns:repeat(5,1fr);border:1px solid #3c4138}.org-metric{padding:22px;border-right:1px solid #3c4138}.org-metric:last-child{border:0}.org-metric strong{font-size:34px;display:block}.org-metric span{font-size:12px;color:#9fa49c;text-transform:uppercase}.org-grid{display:grid;grid-template-columns:1.2fr .8fr;gap:22px;margin-top:25px}.org-panel{border:1px solid #363b34;background:#151815;padding:26px}.org-panel.light{background:#eee5d8;color:#171917;border-color:#eee5d8}.org-panel h2{text-transform:uppercase;font-size:28px;margin:0 0 20px}.queue{display:grid;gap:10px}.queue-item{display:grid;grid-template-columns:1fr auto;gap:15px;align-items:center;border-top:1px solid #3b4039;padding-top:14px}.queue-item:first-child{border-top:0;padding-top:0}.queue-item span{display:block;color:#9fa49c;font-size:12px;margin-top:5px}.queue-item a{background:#e86619;color:white;padding:10px 14px;text-decoration:none;font-size:12px;font-weight:900}.quick-links{display:grid;gap:12px}.quick-link{display:block;border:1px solid #bfb2a1;padding:18px;color:#171917;text-decoration:none}.quick-link strong,.quick-link span{display:block}.quick-link span{color:#666a64;font-size:13px;margin-top:6px}.alert{margin-top:18px;color:#efb078}
    @media(max-width:900px){.org-metrics{grid-template-columns:1fr 1fr}.org-metric{border-bottom:1px solid #3c4138}.org-grid{grid-template-columns:1fr}.org-hero{display:block}.queue-item{grid-template-columns:1fr}.queue-item a{text-align:center}}
  `}</style>
  <section className="org-hero"><div><p className="org-kicker">Legends Core · Organização</p><h1>Centro de operações</h1><p>Acompanhe homologações, horários de passagem e rankings especiais. A organização atua somente nas exceções e na configuração técnica das etapas.</p></div></section>
  <div className="org-content"><section className="org-metrics"><div className="org-metric"><strong>{summary?.total??"—"}</strong><span>envios</span></div><div className="org-metric"><strong>{summary?.validated??"—"}</strong><span>homologadas</span></div><div className="org-metric"><strong>{summary?.review??"—"}</strong><span>em revisão</span></div><div className="org-metric"><strong>{summary?.rejected??"—"}</strong><span>rejeitadas</span></div><div className="org-metric"><strong>{summary?.pending??"—"}</strong><span>pendentes</span></div></section>
  {error?<p className="alert">{error}</p>:null}
  <section className="org-grid"><article className="org-panel"><h2>Fila prioritária</h2>{queue.length?<div className="queue">{queue.map(item=><div className="queue-item" key={item.id}><div><strong>{item.athlete?.full_name??"Atleta"} · {item.stage?.name??"Etapa"}</strong><span>{item.activity?.name??"Atividade"} · cobertura {item.coverage_percent??"—"}%</span></div><a href={`/passport/organizacao/revisoes?validation=${item.id}`}>Analisar</a></div>)}</div>:<p style={{color:"#9fa49c"}}>Nenhuma atividade aguardando revisão.</p>}</article>
  <aside className="org-panel light"><h2>Acessos rápidos</h2><div className="quick-links"><a className="quick-link" href="/passport/organizacao/revisoes"><strong>Fila de revisões</strong><span>Aprovar, rejeitar e registrar observações.</span></a><a className="quick-link" href="/passport/organizacao/checkpoints"><strong>Checkpoints e segmentos</strong><span>Posicionar pontos e criar subidas ou sprints.</span></a><a className="quick-link" href="/passport/organizacao/rankings"><strong>Rankings de trechos</strong><span>Comparar horários e tempos por atleta.</span></a><a className="quick-link" href="/passport/organizacao/validacao"><strong>Validação assistida</strong><span>Testar uma atividade ou GPX manualmente.</span></a><a className="quick-link" href="/passport/organizacao/rotas"><strong>Rotas oficiais</strong><span>Enviar novas versões dos GPXs.</span></a></div></aside></section></div></main>;
}
